version: '3'

services:
  compacter:
    container_name: compacter
    restart: unless-stopped
    build:
      context: ./Compacter
      dockerfile: Dockerfile
    networks:
      - back

  exposer:
    container_name: exposer
    restart: unless-stopped
    build:
      context: ./Exposer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - back
      - internet
    environment:
      API_KEY: ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff

  retriever:
    container_name: retriever
    restart: unless-stopped
    build:
      context: ./Retriever
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - back
      - internet
    environment:
      API_KEY: ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff

  mongodb:
    image: mongo
    restart: unless-stopped
    networks:
      - back
    volumes:
      - mongodb:/data/db

networks:
  back:
    internal: true
  internet:

volumes:
  mongodb:
